name: Sync To Gitea
# on: push
on:
  workflow_run:
    workflows: ["Image Conversion"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Gitea同步文件'
        type: boolean
        required: true
        default: true
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:dongyubin/WP-CDN-02.git" # github仓库地址
          destination-repo: "ssh://git@nas.wangdu.site:47022/dongyubin/WP-CDN-02.git" # gitee仓库地址
