name: Sync Upyun Bucket

on:
  push:
    branches:
      - main

env:
    TZ: Asia/Shanghai # 设置当前环境时区

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - run: rm -rf /github/workspace/.git/ && rm -rf /github/workspace/.github
      - uses: her-cat/upyun-deployer@v1
        with:
          bucket: ${{ secrets.BUCKET }}
          operator: ${{ secrets.OPERATOR }}
          password: ${{ secrets.OPERATOR_PASSWORD }}
          dir: WP-CDN-02/
#           remote_path: /WP-CDN-02/
