name: Sync Upyun Bucket

on:
  push:
    branches:
      - main

env:
    TZ: Asia/Shanghai # 设置当前环境时区

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: deploy-upyun
        uses: dongyubin/upyun-upx-action@main
        env:
          bucket: ${{ secrets.BUCKET }}
          operator: ${{ secrets.OPERATOR }}
          operator_password: ${{ secrets.OPERATOR_PASSWORD }}
          local_path: ./
          remote_path: /WP-CDN-03/
